repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: 'dist'
      - id: check-yaml
        exclude: 'dist'
      - id: check-docstring-first
        exclude: 'dist'
      - id: check-json
        exclude: 'dist'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8' # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: 'dist'
